name: circuit_detector_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  image_picker: ^1.0.7
  path: ^1.8.3
  mime: ^1.0.4
  #camera: ^0.10.5+9
  #path_provider: ^2.1.2
  photo_view: ^0.14.0
  

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  image_cropper: ^11.0.0
  #image: ^4.5.4

  camera: any
  image: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true

  assets:
    - assets/images/home_page_bg.webp
    - assets/images/circuit_placeholder.png
  